name: Deploy


on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@master   # リポジトリのデータを仮想環境にチェックアウトしてくるアクションを実行する

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.0
        with:
          hugo-version: "0.70.0"
            
      - name: Build Project
        run: |
          hugo  --gc --minify                     # ビルド

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with: # shimataro/ssh-key-actionに渡すパラメーター
          private-key: ${{ secrets.SSH_KEY }} # 必須
          public-key: ${{ secrets.SSH_KEY_PUBLIC }} # 必須
          name: id_rsa # 省略可
          known-hosts: ${{ secrets.KNOWN_HOSTS }} # 省略可
      - name: List output files
        run: ls                           # ファイルリストを表示
      - name: chmod
        run: |    
           ssh -v -i /home/runner/.ssh/id_rsa -p 10022 ${{ secrets.SERVER_NAME }} -T

#      # chmod 700 /home/runner/.ssh
#           # chmod 600 /home/runner/.ssh/id_rsa
#       - name: Connect to xserver
#         run: |
#           ssh -v -i /home/runner/.ssh/id_rsa -p 10022 ${{ secrets.SERVER_NAME }} -T
#           ls
      - name: Connect to xserver
        run: |
          scp -r -v -T -i /home/runner/.ssh/id_rsa -P 10022 ${{ secrets.SERVER_NAME }}:chizuchizu.com/public_html/js /home/runner
          ls
# - name: run deploy script
      #   run: bash deploy.sh
